version: "3.8"
services:

  db:
    image: mariadb
    container_name: wp-db
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/db:/var/lib/mysql/

  wordpress:
    build:
      context: ./docker/build/wordpress
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    container_name: wp
    restart: always
    ports:
      - ${WP_PORT}:80
    depends_on:
      db:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - ./src/my-wp-theme:/var/www/html/wp-content/themes/my-wp-theme
